### ISSUE TITLE
Feature: Yield calculator

### ISSUE THREAD

**Issue by franleplant** [LucasJC/rpwhale#31]
As a user I would like to see a new page / section that let's me see projections of expected yield for a given capital. 

Wireframe:
![Note 31 May 2021](https://user-images.githubusercontent.com/1852455/120208793-464c5f00-c204-11eb-8474-00c950c05ddc.jpg)

Users will introduce the capital (in USD probably) they want to invest, an average Price (in wax) to Aether / Hour generated (Price:reward) which is a common way in the community to "value" an assets yield capacity and the calculator will show

- APY
- MPY (montly)
- a chart with the linear projection of the initial capital plus interests
- a chart with the projections of the initial capital plus interest with compounding (montly but we could add settings for different compounding periods).

This could be stage 1 and in stage 2 we could look at these other features:

- automatically extracting the price of a given user's collection from atomic market (how much did she pay for it)
- automatically calculating staking rewards for that collection
- automatically calculate a price:reward ratio
- show the yield information out of the inferred data
- Probably this would be a good estimation at most since different things will fluctuate over time, like asset aeth yield (depending on pool conditions), price of wax, aeth and the land minerals, changes in rplanet config, etc.

**Comment by LucasJC** [comment]
Merged #58 
👏
