### ISSUE TITLE
Feature: Asset yield calculator

### ISSUE THREAD

**Issue by franleplant** [LucasJC/rpwhale#32]
As a user I want to have a section/page to calculate a given asset's (by id, template, etc) reward (aeth/hour).

This basically reuses a lot of the same logic that we have but generalized to any asset.

**Comment by LucasJC** [comment]
First iteration implemented in #38 
This implementation is missing rplanet elements and simple assets

**Comment by LucasJC** [comment]
RPlanet elements added in #39

**Comment by LucasJC** [comment]
Still pending work on simpleassets integration

**Comment by LucasJC** [comment]
#45  all done!
